# Generated by Django 2.0.3 on 2018-03-25 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kruk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KrukComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=60)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('kruk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kruk.Kruk')),
                ('krukacz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
