# Generated by Django 2.0.3 on 2018-03-26 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kruk', '0003_observer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observer',
            name='id',
        ),
        migrations.AlterField(
            model_name='observer',
            name='krukacz',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
